# Generated by Django 4.0.2 on 2022-02-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rooom',
            new_name='Room',
        ),
    ]
